spring.datasource.url=jdbc:oracle:thin:@localhost:1521:FREE
spring.datasource.username=ADV_JAVA
spring.datasource.password=JAVA
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

